In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,20,5, dtype = 'int8')
print(arr)

[ 1  5 10 15 20]


In [4]:
indexes = arr > 5
indexes

array([False, False,  True,  True,  True])

In [7]:
arr[indexes]

array([10, 15, 20], dtype=int8)

In [8]:
arr[indexes & (arr < 20)]

array([10, 15], dtype=int8)

In [9]:
arr_copy  = arr.copy()
arr_copy[(arr_copy > 5) & (arr_copy < 20)] = 0

In [11]:
print(arr, id(arr))
print(arr_copy, id(arr_copy))

[ 1  5 10 15 20] 140037857157136
[ 1  5  0  0 20] 140037546323152


In [12]:
matrix = np.array([[19,  4, 43],[ 8, 96, 80],[ 6, 99, 35]])
np.where(matrix > 50, 0, 1) #where(condicion, valor si, valor si la condicion no se cumple)


array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])

In [13]:
arr = np.arange(1,11)

def number_is_even(num):
    return num % 2 == 0


number_is_even(arr)

lambda_func = lambda x: x % 2 == 0

lambda_func(arr)

array([False,  True, False,  True, False,  True, False,  True, False,
        True])