In [2]:
import numpy as np

In [1]:
list(range(0,10)) #a non numpy object

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,10) #numpy object (from, until)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,20, 2) #numpy object (from, until, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.zeros(3) # Vector

array([0., 0., 0.])

In [7]:
np.zeros((10,10)) # 10 x 10 matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones(3) # Vector

array([1., 1., 1.])

In [9]:
np.ones((10,10)) # 10 x 10 matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,20, 10) #distribution

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand()

0.9676333280053575

In [14]:
np.random.rand(4)

array([0.59770027, 0.98901427, 0.30643946, 0.88704516])

In [18]:
np.random.rand(4,4) # 4 x 4 matrix

array([[0.95883075, 0.89516737, 0.8236407 , 0.31475056],
       [0.27945897, 0.24994745, 0.69677434, 0.76806788],
       [0.55239176, 0.9041042 , 0.8440485 , 0.14783099],
       [0.5469565 , 0.72676036, 0.94786013, 0.3038537 ]])

In [17]:
np.random.randint(0,5)

3

In [19]:
np.random.randint(1,10,(5,5))# 5x5 matrix

array([[3, 2, 2, 3, 5],
       [4, 9, 3, 7, 9],
       [3, 5, 8, 3, 5],
       [7, 6, 7, 7, 2],
       [8, 2, 7, 3, 1]])