In [11]:
import numpy as np
import random as rm

In [29]:
ra = lambda n: [rm.randint(0,10) for x in range(n)]

# ARRAY DIMENSIONS

In [12]:
scalar = np.array(54)
scalar.ndim

0

In [13]:
vector = np.array([1,2,3])
vector.ndim

1

In [49]:
matrix = np.array([ra(3), ra(3), ra(3)])
print(matrix, "\n")
print("1: ", matrix[:,1])
print("2: ", matrix[2], "\n")
print(f'Dimensions: {matrix.ndim}')


[[ 3  5  9]
 [ 3  4 10]
 [ 0  1  8]] 

1:  [5 4 1]
2:  [0 1 8] 

Dimensions: 2


In [51]:
tensor = np.array([[ra(3),ra(3),ra(3)],[ra(3),ra(3),ra(3)],[ra(3),ra(3),ra(3)]])
print(tensor, "\n")
print(f'Dimensions: {tensor.ndim}')

[[[ 4  5  6]
  [ 4  5  5]
  [ 2  3  3]]

 [[ 0  8  7]
  [10  3  0]
  [ 1  0  3]]

 [[ 9  0  2]
  [ 2  3  9]
  [ 6  0  8]]] 

Dimensions: 3


# Add or delete array dimensions

In [52]:
vector = np.array([1,2,3], ndmin = 10)
print(vector, "\n")
print("Dimensions: ", vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 

Dimensions:  10


In [53]:
# Expand in axis
expand = np.expand_dims(np.array([1,2,3]), axis = 0)
print(expand, "\n")
print("Dimensions: ", expand.ndim)

[[1 2 3]] 

Dimensions:  2


In [55]:
print(vector, "\n")
print("Dimensions: ", vector.ndim)

print('\n',"-----"*5, '\n')

vector_2 = np.squeeze(vector) #Correct dimension
print(vector_2, "\n")
print("Dimensions: ", vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 

Dimensions:  10

 ------------------------- 

[1 2 3] 

Dimensions:  1


# Testing


In [68]:
#Axis show
print("Default")
print(np.array([[1,2,3],[4,5,6]]), '\n')

print("Expansion in 0")
expand0 = np.expand_dims(np.array([[1,2,3],[4,5,6]]), axis = 0)
print(expand0, "\n")

print("Expansion in 1")
expand1 = np.expand_dims(np.array([[1,2,3], [4,5,6]]), axis = 1)
print(expand1, "\n")


Default
[[1 2 3]
 [4 5 6]] 

Expansion in 0
[[[1 2 3]
  [4 5 6]]] 

Expansion in 1
[[[1 2 3]]

 [[4 5 6]]] 



In [61]:
tensor_5 = np.array([[[[ra(3),ra(3),ra(3)],[ra(3),ra(3),ra(3)]],[[ra(3),ra(3),ra(3)],[ra(3),ra(3),ra(3)]]],[[[ra(3),ra(3),ra(3)],[ra(3),ra(3),ra(3)]],[[ra(3),ra(3),ra(3)],[ra(3),ra(3),ra(3)]]], [[[ra(3),ra(3),ra(3)],[ra(3),ra(3),ra(3)]],[[ra(3),ra(3),ra(3)],[ra(3),ra(3),ra(3)]]]])
print("Dimensions: ", tensor_5.ndim)

expand = np.expand_dims(tensor_5, axis = 0)
print("Dimensions: ", expand.ndim)

tensor_5d  = np.squeeze(expand) #Correct dimension
print(tensor_5d , "\n")
print("Dimensions: ", tensor_5d .ndim)

Dimensions:  5
Dimensions:  6
[[[[[ 7  6  4]
    [ 6  3  3]
    [ 8  5  0]]

   [[ 7  7  8]
    [ 1  1  0]
    [ 8  3  2]]]


  [[[ 9  7  0]
    [ 8  4  5]
    [ 2  0  4]]

   [[ 4  7  1]
    [ 6 10  2]
    [ 6  2 10]]]]



 [[[[ 0  7  3]
    [ 4  8  2]
    [10  2 10]]

   [[ 6  9  5]
    [ 7  2  9]
    [10  4  8]]]


  [[[ 4  4  9]
    [ 2  2  8]
    [ 8  5  4]]

   [[10  0  1]
    [ 2  0  2]
    [ 5  4  1]]]]



 [[[[ 8  5  0]
    [ 1  4  8]
    [ 1  4  5]]

   [[ 3  5  7]
    [ 6  8  4]
    [10  5  1]]]


  [[[ 2  3  6]
    [ 3  4  5]
    [ 6  9  1]]

   [[ 3  0  7]
    [ 0  7  9]
    [ 1  1  6]]]]] 

Dimensions:  5
