In [18]:
import numpy as np

In [19]:
# Default python list
array = [1,2]
array

[1, 2]

In [20]:
# Default python list
array * 3

[1, 2, 1, 2, 1, 2]

In [21]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Operations

In [22]:
art = arr.copy()
art

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
art * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
1 / art

/tmp/ipykernel_11389/4194531785.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / art


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [25]:
art ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [26]:
art + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
m = art.reshape(2,5)
matrix = m.copy()
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
m - matrix #restar

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
#Producto punto: es una operación algebraica que toma dos vectores y retorna un escalar, y que satisface ciertas condiciones.
np.matmul(m, matrix.T) # Producto punto, se necesita que convergan las filas y columnas

array([[ 30,  80],
       [ 80, 255]])

In [30]:
m @ matrix.T # Simplified version 

array([[ 30,  80],
       [ 80, 255]])

# Unique operator

In [32]:
art

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
art[art  % 2 == 0] = 11
art

array([11,  1, 11,  3, 11,  5, 11,  7, 11,  9])

In [34]:
unique = np.unique(art)
unique

array([ 1,  3,  5,  7,  9, 11])

In [35]:
art

array([11,  1, 11,  3, 11,  5, 11,  7, 11,  9])

In [37]:
unique, ocurrence = np.unique(art, return_counts = True)
print(unique)
ocurrence

[ 1  3  5  7  9 11]


array([1, 1, 1, 1, 1, 5])