In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2)) # Matrix 3 x 2
arr

array([[4, 8],
       [8, 3],
       [7, 9]])

In [4]:
arr.shape

(3, 2)

In [5]:
arr.reshape(1,6) # Matrix 1 x 6 = Vector

array([[4, 8, 8, 3, 7, 9]])

In [6]:
arr.reshape(2,3) # Matrix 2 x 3

array([[4, 8, 8],
       [3, 7, 9]])

# Reshape according to different sources

In [12]:
arr

array([[4, 8],
       [8, 3],
       [7, 9]])

In [13]:
#default
np.reshape(arr,(2,3))

array([[4, 8, 8],
       [3, 7, 9]])

In [14]:
# 'C' language
np.reshape(arr,(2,3),'C') #per rows

array([[4, 8, 8],
       [3, 7, 9]])

In [16]:
# 'Fortran' language
np.reshape(arr,(2,3),'F') #per columns

array([[4, 7, 3],
       [8, 8, 9]])

In [17]:
#according to the default configuration of memory saving in my system
np.reshape(arr,(2,3),'A')

array([[4, 8, 8],
       [3, 7, 9]])

In [18]:
#imposible array reshape
np.reshape(arr,(5,7))

ValueError: cannot reshape array of size 6 into shape (5,7)