In [1]:
import numpy as np

In [2]:
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
piece = arr[0:5]
piece

array([0, 2, 4, 6, 8])

In [6]:
piece[:] = 0 # Cambiar todos los valores a 0
piece

array([0, 0, 0, 0, 0])

In [7]:
arr #xddd - Se modifica la estructura general aunque la intencion sea cambiar otra referencia

array([ 0,  0,  0,  0,  0, 10, 12, 14, 16, 18])

In [9]:
arr_copy = arr.copy() # Evitamos que al moficar algo se modifique el objeto padre
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
arr # No se modifico, se usaron otros espacios de memoria

array([ 0,  0,  0,  0,  0, 10, 12, 14, 16, 18])

In [12]:
# Espacios de memoria, que hace referencia a que. Muy util para otros problemas.
print("Original array: ",id(arr))
print("Copy array: ",id(arr_copy))

Original array:  139918410226288
Piece array:  139917958359408
Copy array:  139917958359888
