In [1]:
import numpy as np

# Numpy arrange
Create a range of data with numpy

In [10]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [11]:
m = np.linspace(0,10,5, dtype=np.float64)
m

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Some data types

• .dtype: Para poder saber cuál es el tipo de dato está usando el array
• .astype: Para poder cambiar el tipo de dato qué está usando el array

In [4]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [3]:
arr = np.array([1,2,3,4], dtype = 'float64')
arr.dtype

dtype('float64')

In [5]:
arr = arr.astype(np.float64)

In [6]:
arr

array([1., 2., 3., 4.])

In [7]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [8]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [9]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)