In [3]:
import numpy as np

In [10]:
arr = np.random.randint(1,20,10)
arr

array([14, 10,  6, 16, 15,  6, 15, 15,  6,  1])

In [11]:
matrix = arr.reshape(5,2)
matrix

array([[14, 10],
       [ 6, 16],
       [15,  6],
       [15, 15],
       [ 6,  1]])

In [12]:
arr.max()

16

In [20]:
matrix.max(1) #max(AXIS)

array([14, 16, 15, 15,  6])

In [22]:
print(arr)
arr.argmax()

[14 10  6 16 15  6 15 15  6  1]


3

In [23]:
print(matrix)
matrix.argmax()

[[14 10]
 [ 6 16]
 [15  6]
 [15 15]
 [ 6  1]]


3

In [26]:
print(matrix)
matrix.argmax(1) #argmax(AXIS) -----> index

[[14 10]
 [ 6 16]
 [15  6]
 [15 15]
 [ 6  1]]


array([0, 1, 0, 0, 0])

In [28]:
print(arr)
arr.min()

[14 10  6 16 15  6 15 15  6  1]


1

In [29]:
arr.argmin()

9

In [31]:
print(matrix)
matrix.argmin(1) #argmin(AXIS) -----> index

[[14 10]
 [ 6 16]
 [15  6]
 [15 15]
 [ 6  1]]


array([1, 0, 1, 0, 1])

In [34]:
print(arr)
arr.ptp() #peak to peak -> del pico más alto al mas bajo existe una diferencia de:

[14 10  6 16 15  6 15 15  6  1]


15

In [35]:
print(matrix)
matrix.ptp(1)  #argmin(AXIS) -> diferencia ente picos, filtrado por el indice 1

[[14 10]
 [ 6 16]
 [15  6]
 [15 15]
 [ 6  1]]


array([ 4, 10,  9,  0,  5])

In [37]:
arr.sort()
arr

array([ 1,  6,  6,  6, 10, 14, 15, 15, 15, 16])

In [41]:
print(arr)
np.percentile(arr, 50) # percentile(array, NUMERO DE PROCENTAJE) -> para buscar la mediana, el numero más bajo, etc

[ 1  6  6  6 10 14 15 15 15 16]


12.0

In [42]:
np.median(arr) # Mediana de un arreglo

12.0

In [44]:
print(matrix)
np.median(matrix,1)# Mediana por el eje 1

[[ 1  6]
 [ 6  6]
 [10 14]
 [15 15]
 [15 16]]


array([ 3.5,  6. , 12. , 15. , 15.5])

In [45]:
print(arr)
np.std(arr) # Desviacion estandar: cuantificar la variación o la dispersión de un conjunto de datos numéricos.​

[ 1  6  6  6 10 14 15 15 15 16]


5.043808085167397

In [46]:
print(arr)
np.var(arr) #Varianza: es una medida de dispersión definida como la esperanza del cuadrado de la desviación de dicha variable respecto a su media.

[ 1  6  6  6 10 14 15 15 15 16]


25.44

In [48]:
print(arr)
np.mean(arr) #Media


[ 1  6  6  6 10 14 15 15 15 16]


10.4

In [53]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

np.concatenate((a,b),axis = 0) # Concatenate, need a correct array dimensions

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.concatenate((a,b),axis = 1) # Concatenate, need a correct array dimensions

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [55]:
b.T # array.T  -> transponer un array, forma abreviada de un reshape

array([[5],
       [6]])

In [56]:
np.concatenate((a,b.T),axis = 1) # Concatenate, need a correct array dimensions

array([[1, 2, 5],
       [3, 4, 6]])