In [2]:
import numpy as np
import random as ra

In [3]:
x = [i for i in range (0,10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
object = np.array(x)
print(type(object))
object

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# List split:
https://www.delftstack.com/es/howto/python/python-split-list-into-chunks/

In [5]:
n, o = 3, [m for m in range(30)]
p = [ o[i : i + n]  for i in range(0, len(o), n)] # len(from, until, intervals )
matrix = np.array(p)
matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [6]:
#index , matrix[row, column]
matrix[0][1]

1

In [7]:
#slicing, array[from:until:intervals]
print(x)
print(x[2:7])
x[2:7:2]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6]


[2, 4, 6]

In [8]:
print(matrix)
matrix[4:,1]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


array([13, 16, 19, 22, 25, 28])

In [9]:
#third-dimension matrix
l = lambda : [ra.randint(0,10), ra.randint(0,10)]
y = [[l(),l(),l()] for i in range(3)]
thematrix = np.array(y)
thematrix

array([[[ 8,  3],
        [ 2,  0],
        [ 7,  3]],

       [[ 1,  5],
        [ 2, 10],
        [ 9,  7]],

       [[ 9,  3],
        [ 3,  7],
        [10,  6]]])

In [10]:
thematrix[0,2,1]

3